name: Dating App CI

on:
  push:
    paths:
      - "backend/app/**"
      - "backend/tests/**"
  pull_request:
    paths:
      - "backend/app/**"
      - "backend/tests/**"

jobs:
  setup:
    uses: ./.github/workflows/setup-dependencies.yml

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.setup.outputs.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          cd backend
          poetry install
      - name: Run Ruff
        run: |
          cd backend
          poetry run ruff check app tests

  type-check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.setup.outputs.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          cd backend
          poetry install
      - name: Run Mypy
        run: |
          cd backend
          poetry run mypy app tests

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.setup.outputs.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          cd backend
          poetry install
      - name: Run Pytest
        run: |
          cd backend
          poetry run pytest tests
